const LARGURA = 1100;
const ALTURA = 1300;
const MEIA_LARGURA = LARGURA / 2;
const MEIA_ALTURA = ALTURA / 2;

const COR_DE_FUNDO = 0;

const CRIATURA_TAMANHO = 10;
const CRIATURAS_INICIAIS = 10;
const CRIATURA_VIDA_INICIAL = 1000;
const CRIATURA_VELOCIDADE_MINIMA = 0.01;
const CRIATURA_VELOCIDADE_MAXIMA = 0.09;
const DESGASTE_MINIMO = 0.001;
const DESGASTE_MAXIMO = 0.005;

const PENALIDADE_DE_COLISAO = 0.0001;
const FATOR_REPULSAO = 1.5;

const GENOMA_VELOCIDADE_INICIAL = 1;
const GENOMA_VELOCIDADE_MINIMA = 1.2;
const GENOMA_VELOCIDADE_MAXIMA = 1.9;
const GENOMA_CAMPO_DE_VISAO = CRIATURA_TAMANHO + 100;

const ALIMENTO_TAMANHO = 4;
const ALIMENTOS_INICIAIS = 50;
const ALIMENTO_VALOR = 10;
const ALIMENTO_VELOCIDADE = 0.1;

const TAXA_DE_PERDA_DE_VIDA = 0.1;

let PAINEL;
let AMBIENTE, ALIMENTO;
